### ISSUE TITLE
Move translations to Foreman-project on transifex

### ISSUE THREAD

**Issue by m-bucher** [theforeman/foreman_fog_proxmox#109]
Right now I think the translations are kinda orphaned as the original [Transifex-project](https://www.transifex.com/foremanfogproxmox/httpsgithubcomtristanrobertforeman_fog_proxmox/) probably was not migrated after the plugin was moved on github.
@bkearney I propose to open a new sub-project for the [Foreman-Transifex-project](https://www.transifex.com/foreman/foreman/content/), if this is ok for @tristanrobert 

This would enable solving #84

**Comment by tristanrobert** [comment]
Yes. You need to add a locales/pt/foreman_fog_proxmox.po file. A PR is welcome. I don't speak portugese :smile:

**Comment by tristanrobert** [comment]
@m-bucher Done! You can now translate in transifex project: https://www.transifex.com/foremanfogproxmox/public/

**Comment by m-bucher** [comment]
Thanks @tristanrobert , can you also please check if the link to the `.pot` file in transifex is correct?
I only see one string on tranisfex right now.

This might help: https://community.theforeman.org/t/plugin-translations-workflow-questions/15838/17

**Comment by tristanrobert** [comment]
To sync pot files Transifex needs to be installed in the repo. I am not owner of it. I have to post a request to the foreman team.

**Comment by tristanrobert** [comment]
I have posted the request: https://community.theforeman.org/t/request-to-install-transifex-in-foreman-fog-proxmox-repo/17672

**Comment by m-bucher** [comment]
Most foreman-plugins are also added to transifex as resources of the foreman project, which gives you the option to re-use some of the strings they already translated for different resources.

But then again you rely on them to manage the transifex stuff :man_shrugging:

**Comment by tristanrobert** [comment]
Done: https://www.transifex.com/foreman/foreman/foreman_fog_proxmox/

**Comment by tristanrobert** [comment]
Forget: https://www.transifex.com/foremanfogproxmox/public/
