### ISSUE TITLE
Can't provision new VMs proxmox 5.4 fog_proxmox 0.8

### ISSUE THREAD

**Issue by mbj047** [theforeman/foreman_fog_proxmox#112]
**Describe the bug**
Attempting to deploy new host on proxmox 5.4 error message 'Failure: undefined method `extract_pcid' for Fog::Proxmox::CpuHelper:Module Did you mean? extract' appears.

**To Reproduce**
When attempting to create a new host with foreman_fog_proxmox 0.8.0
1. select deploy on proxmox instance and the Virtual Machine tab turns red. 
2. Click on the Virtual Machine Tab the error message 'Failure: undefined method `extract_pcid' for Fog::Proxmox::CpuHelper:Module Did you mean? extract' appears with no other options.

**Expected behavior**
The virtual machine tab to populate with the different VM options.

**Environment**
Tested OSs - Centos 7, Ubuntu 18.04, and Debian 9. 
Proxmox 5.4.13
Foreman 1.23
foreman_fog_proxmox-0.8.0
fog-proxmox-0.8.2

**Comment by tristanrobert** [comment]
Foreman_fog_proxmox 0.8.1 would be suitable to fog_proxmox 0.8.3. They would be released this week. 0.8.0 is only suitable with fog_proxmox < 0.8.2.

**Comment by mbj047** [comment]
Ok Thanks for your reply and hard work. I will close this and try again when you release the new version.
