### ISSUE TITLE
Compatibility with Proxmox 6.x

### ISSUE THREAD

**Issue by BloodyIron** [theforeman/foreman_fog_proxmox#113]
I see the latest version listed as supported is Proxmox 5.4.

Proxmox 6.0 has been out for a good while now, any chance we can get it added please?

**Comment by tristanrobert** [comment]
I release 0.8.1 in hours and I work on 0.9.0 to provide Proxmox 6.0. You can contribute to help: code, doc, translate or [sponsor me](https://github.com/sponsors/tristanrobert)!

**Comment by tristanrobert** [comment]
Depends on [fog-proxmox#52](https://github.com/fog/fog-proxmox/issues/52)

**Comment by BloodyIron** [comment]
Woot! :D
