### ISSUE TITLE
Foreman plugin install uses 0.8.2-1

### ISSUE THREAD

**Issue by Scifire** [theforeman/foreman_fog_proxmox#117]
Just installed the plugin via the foreman OS plugin install method (`apt install ruby-foreman-fog-proxmox`) 
Unfortunately, this installs version 0.8.2 of the plugin. 

What is needed to update this to the latest version of the plugin? Could we assist here maybe? 
We happily  recognized that there were a lot bug fixes made recently so we would like to give it a try.

**Comment by tristanrobert** [comment]
@Scifire  I have push the code a few days ago (0.9.1 and 0.9.2). 
If you need it, you could vote for these PR I have already submitted to the packaginig team: 
* https://github.com/theforeman/foreman-packaging/pull/4449
* https://github.com/theforeman/foreman-packaging/pull/4406
* https://github.com/theforeman/foreman-packaging/pull/4405
* https://github.com/theforeman/foreman-packaging/pull/4308

**Comment by Scifire** [comment]
@tristanrobert Thanks for the fast answer and you´re work at all :)
