### ISSUE TITLE
Automatically Generate MAC Address

### ISSUE THREAD

**Issue by dandrzejewski** [theforeman/foreman_fog_proxmox#119]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow Proxmox to generate a MAC address for new VMs.

**Describe the solution you'd like**
I should be able to leave the MAC address field blank (or put in some value like 11:22:33:44:55) and have Proxmox override it with a "real" MAC address.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tristanrobert** [comment]
It is already the case. But if you put the mac adress, promox will save it.

**Comment by dandrzejewski** [comment]
There's a note in the documentation that if you leave the MAC address empty, it will allow the compute resource to generate one, so I assume this works for other compute resources.

**Comment by tristanrobert** [comment]
By default if you leave empty, proxmox will generate a mac address.
