### ISSUE TITLE
Choose node in cluster when creating and updating host

### ISSUE THREAD

**Issue by tristanrobert** [theforeman/foreman_fog_proxmox#126]
**What is it possible to do now?**
* When creating a compute resource, we must associate a default node.
* When creating a host, it is possible to choose the compute resource and a node is chosen by default.

**What could be done better?**
 * Changing the node when creating a host: the one by default is linked to the compute resource.
* Changing the node after the host is created (so updating its configuration), it implies migrating the host from one node to another one.
* Creating a compute resource without associating a default node. Then the node must be selected each time we create a host (vm or container).

Would you like to keep associating a default node to a compute resource?

- [ ] Yes
- [x] No

**Comment by tristanrobert** [comment]
If we remove the default node from the compute resource, it could be easier and cleaner to users.

**Comment by hlawatschek** [comment]
Hi Tristan,
thanks for starting this discussion.
Let me answer your questions inline.

> **What is it possible to do now?**
> 
> * When creating a compute resource, we must associate a default node.
> * When creating a host, it is possible to choose the compute resource and a node is chosen by default.
* Updating a host configuration can be done for all hosts on all cluster nodes (introduced with PR #124)
> 
> **What could be done better?**
> 
> * Changing the node when creating a host: the one by default is linked to the compute resource.

This would be solved by PR #124 

> * Changing the node after the host is created (so updating its configuration), it implies migrating the host from one node to another one.

This would be a great feature.

> * Creating a compute resource without associating a default node. Then the node must be selected each time we create a host (vm or container).

I prefer the default node configuration in favor of forcing the user to select a node every time. But the "default" node could also be the first available node for the start.
In future it would be nice to have an automated node selection mechanism based on some configurable metrics like current CPU usage, disk usage, ...
 
> Would you like to keep associating a default node to a compute resource?

* []  Yes 
* [x]  No - But a default node should be predefined during host creating (e.g. first available node.)
