### ISSUE TITLE
Missing LXC proxmox interface when a compute profile is used.

### ISSUE THREAD

**Issue by jacac** [theforeman/foreman_fog_proxmox#127]
Using a compute profile the Proxmox network fields do not show up. They are in the page but disabled, Going back to the `Virtual Machine` tab and switching the `Type` back and forth makes the network field show up again. Looks like something is not triggered when the `Type` field is set by the compute profile.

1. Go to `Infrastructure` -> `Compute Profile`
2. Create a profile with `Type` -> `LXC container`
3. Fill in some nic information. I had `Name` and `Bridge` set
4. Got to `Hosts` -> `Create Host`
5. Select 'Deploy on' to a Proxmox computer resource and the `Compute profile` to the one created before
6. `Virtual Machine` information should be set by the compute profile.
7. Select `Interfaces` tab
8. Click on `Edit`
9. Missing input fields

**Expected behavior**
Fields for Proxmox nic information `Proxmox ( from profile XXX)` should show up.

This is how it looks 
![image](https://user-images.githubusercontent.com/422293/73559636-47039400-440a-11ea-9b0d-a9f1cec93a06.png)

Here is the HTML for the fields.
![image](https://user-images.githubusercontent.com/422293/73559996-02c4c380-440b-11ea-870a-649069225610.png)

It also looks to me that f object in not initialized. Should the id fieldset id `container_network_` not add index from the f object?
https://github.com/theforeman/foreman_fog_proxmox/blob/56f41a1db8ea8d6e291ffb2d93b52386adacfa71/app/views/compute_resources_vms/form/proxmox/container/_network.html.erb#L20

**Additional context**
This is happening for 9.0.4

**Comment by tristanrobert** [comment]
Indeed no f.index and no vm type (lxc or qemu) are set.

**Comment by tristanrobert** [comment]
Fixed in v0.10.0
