### ISSUE TITLE
Separate start vm after creation from always start on cluster boot.

### ISSUE THREAD

**Issue by tristanrobert** [theforeman/foreman_fog_proxmox#133]
The `Start on boot?` box is now related to `onboot` Proxmox config option which means that the vm will start on cluster bootup.

The idea is to seperate the two options:

- A `Start on system boot?` box related to `onboot` Proxmox config option: the vm boot always when the cluster reboot.
- A `Start after creation?` box to start the vm after its creation only.

**Comment by hlawatschek** [comment]
Thanks @tristanrobert, I'd prefer to have both options separately.
You might (normally you do) want to start the vm directly after host creation in order to start the network installation. This doesn't include that you want to have the vm started after the proxmox server/cluster is started.

**Comment by tristanrobert** [comment]
The idea is indeed to offer the two options :-)
