### ISSUE TITLE
Remove fields from create host which are irrelevant but required

### ISSUE THREAD

**Issue by jacac** [theforeman/foreman_fog_proxmox#134]
For the LXC type remove fields under `Create Host`-> `Operating System` (Not sure if they are used for Qemu) They are required but not used:
- [] `Media`
- [] `Partition Table`
- [] `Custom Partition Table`
- [] `Root Password` (This is set in `Virtual Machine`)

**Comment by tristanrobert** [comment]
It is a foreman core feature. You should post this issue in the adequate repo: https://github.com/theforeman/foreman
