### ISSUE TITLE
Add VM to pool

### ISSUE THREAD

**Issue by blinkiz** [theforeman/foreman_fog_proxmox#135]
Hello
Thanks for a great product addon to Foreman!

I can not find a feature to add VMs to a pool in Proxmox. The future seems to be [implemented in fog_proxmox](https://github.com/fog/fog-proxmox/issues/13) but not here?

**Comment by tristanrobert** [comment]
Thnak you. You are right this feature is not enabled in the foreman plugin. If many users ask for it, it could be done :-)

**Comment by blinkiz** [comment]
Nicely done! Am looking forward to using this feature when it goes into nightly at foreman plugins.
