### ISSUE TITLE
Only needing role PVEVMAdmin in a pool for this plugin to work

### ISSUE THREAD

**Issue by blinkiz** [theforeman/foreman_fog_proxmox#136]
Hello.
Again, thanks for a great product! I have a feature request. Maybe it should be against fog_proxmox instead of here. I do not know the difference :slightly_smiling_face: 

I have a Proxmox cluster with a couple of hundred virtual machines in production with paying customers. Am a little bit afraid to give Foreman 'Administrator' right to this cluster. Foreman becomes another tool that has unlimited power over the cluster that I need to protect.
I would like to give Foreman read rights everywhere but only CRUD permission in a specific pool.
With this feature it also becomes possible to control VMs on Proxmox where you do not have administrator rights. Maybe you are just buying a pool from a hosting company and you have PVEVMAdmin role on a one or more pools.

Well, this may have low interest in this community but now I have said it anyway :slightly_smiling_face:

**Comment by tristanrobert** [comment]
Duplicate with #135

**Comment by tristanrobert** [comment]
Maybe you could create a specific user with these restricted permissions and connect your compute ressource int the plugin with this role and not the root user.

**Comment by blinkiz** [comment]
> Maybe you could create a specific user with these restricted permissions and connect your compute ressource in the plugin with this role and not the root user.

Hi. Thanks for replying. Yeah, that is the goal of this feature request. :slightly_smiling_face:
It does not currently work.

I have many pools in a bigger Proxmox cluster where customers have PVEVMAdmin role in one or more pools. I then have bash scripts running that's making sure customers do not do anything stupid with the configuration of VMs and killing that VM if that is the case. And then billing what they have used last month. Proxmox is not build for a reseller structure but that is how I use it.

My need can be solved in other ways but I thought I request the feature anyway. I really need #135 but this feature is more nice to have. At the moment anyway.
