### ISSUE TITLE
Proxmox extension for foreman_bootdisk

### ISSUE THREAD

**Issue by Manisha15** [theforeman/foreman_fog_proxmox#138]
**New feature**
I am trying to add a proxmox extension in foreman_bootdisk, where bootdisk based deployment of host is possible for proxmox compute resource.

**Possible Solution**
The idea is to add cdrom iso image to boot in, which is first uploaded to server and then can be attached for boot in. 

**Problem**
I am trying to upload iso with cdrom which should create new volume  using **save_volume** functionality of foreman_fog_proxmox, that can be used to attach it to boot in. But  I am unable to create new volume as it throws error **unable to parse directory volume name '0'**. 
Can you point me in some direction, how can I add new volume for iso which attached as cdrom.

**Comment by tristanrobert** [comment]
In proxmox, disk id should start with: `sata`, `ide`, `virtio` or `scsi` and end whith an integer from 0 to 99. For example: `ide0`. See [API docs](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config) POST or PUT method.

**Comment by Manisha15** [comment]
Thanks for your suggestions. I tried to upload iso as **POST /api2/json/nodes/{node}/storage/{storage}/upload**  but it gives **EndOfFile** error. 

I saw you had also implemented something similar https://github.com/fog/fog-proxmox/commit/3288b16a09cd489694c0143ddc8c7aa455de29ae but didn't merge. May I know the reason or did you create an alternative method for this.

**Comment by tristanrobert** [comment]
So if I understand you would like a new feature: uploading an image in the cluster? I didn't merge it because it would complicate and weaken the code. It needs an upload form with big files which seems a bit risky.  But maybe another simplier solution would be acceptable.

**Comment by tristanrobert** [comment]
https://github.com/theforeman/foreman_bootdisk/pull/90 :+1:

**Comment by Manisha15** [comment]
Closing the issue as we have PR in foreman_bootdisk  https://github.com/theforeman/foreman_bootdisk/pull/90
