### ISSUE TITLE
storage 'local' is disabled

### ISSUE THREAD

**Issue by taniahagan** [theforeman/foreman_fog_proxmox#141]
Hi, 

I am currently using foreman version 2.0.0-rc2 and proxmox 1.10.0, and I am trying to create image from a compute resource but I am seeing the following error: 

Expected([200]) <=> Actual(500 InternalServerError) excon.error.response :body => "{\"data\":null}" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "13" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Mon, 23 Mar 2020 12:00:00 GMT" "Expires" => "Mon, 23 Mar 2020 12:00:00 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => “<prox host>” :local_address => “<ip addr>” :local_port => 54556 :path => "/api2/json/nodes/<host>/storage/local/content" :port => 8006 :reason_phrase => "storage 'local' is disabled" :remote_ip => “<ip addr>” :status => 500 :status_line => "HTTP/1.1 500 storage 'local' is disabled\r\n"

Is there a way in the plugin to point to the correct storage location? 

Thank You, 
Tania

**Comment by tristanrobert** [comment]
1. Plugin is not yet tested with foreman 2.0
2. your storage named "local" is disabled. You should see in your proxmox why it is disabled. When you create an image you choose the storage locations in select.
