### ISSUE TITLE
plugin cannot detect all image template types

### ISSUE THREAD

**Issue by hlawatschek** [theforeman/foreman_fog_proxmox#142]
**Describe the bug**

The plugin detects image templates using a RegEx
`app/models/concerns/fog_extensions/proxmox/disk.rb`
```
def templated?
   volid ? volid.match(/^([\w-]+)[:]base-(\d+)-disk-(\d+)/) : false
end 
```
Unfortunately it does not detect templates on all storage types.
e.g.
`local:106/base-106-disk-0.qcow2 `
Should be a valid template

This template works:
`images:base-109-disk-0 `

**To Reproduce**
create an image on local storage and try to use it for host creation

**Expected behavior**
images should be detected on all storage types

**Comment by tristanrobert** [comment]
Can you please give a documentation reference? I don't find what rule proxmox uses to name its images and templates.

**Comment by tristanrobert** [comment]
The only change I see when you modify a vm to a template is the name become: vm-100-disk-0 to base-100-disk-0 in local-lvm and format is still the same: raw.

**Comment by hlawatschek** [comment]
If I remember correctly the RegEx is not sufficient to parse "local:106/base-106-disk-0.qcow2" correctly

**Comment by tristanrobert** [comment]
Can you give me a procedure to create a template volume named: `local:106/base-106-disk-0`? I just have `local-lvm:vm-100-disk-0` disk images (raw).

**Comment by hlawatschek** [comment]
I think its just to have the default storage configuration. 
Probably the storage type dir as local storage in e.g. /var/lib/vz/.
Create a VM using this local storage, then convert to template.

**Comment by tristanrobert** [comment]
By default, when I create a VM I have this disk volume id: `local-lvm:vm-100-disk-0`. See my screenshot.
![Firefox_Screenshot_2020-10-27T17-30-38 652Z](https://user-images.githubusercontent.com/19711088/97339358-c67fa000-1882-11eb-9e48-9ae6dcbb5ade.png)

**Comment by hlawatschek** [comment]
Please try to create a VM on the storage "local". This should be a directory based storage.

**Comment by tristanrobert** [comment]
I have found the doc. This function will be fixed and moved to fog-proxmox Disk class: https://github.com/fog/fog-proxmox/issues/64
