### ISSUE TITLE
`Oops, we're sorry but something went wrong undefined method  type' for nil:NilClass

### ISSUE THREAD

**Issue by MarvinMedia** [theforeman/foreman_fog_proxmox#145]
I am using proxmox version 6 and foreman 1.4.1 and foreman 2.0

Getting "undefined method `first' for nil:NilClass" when trying to power on the VM ,trying to create image from foreman on proxmox compute resource.

**Comment by MarvinMedia** [comment]
Can someone help me solve the problem?

**Comment by hlawatschek** [comment]
Do you have other compute resource plugins installed?

**Comment by tristanrobert** [comment]
Which foreman version are you using? 2.0 or 1.4.1 which is very old!...Which plugin version ? Could you send your logs contaning the error?

**Comment by MarvinMedia** [comment]
> Do you have other compute resource plugins installed?

No.

**Comment by MarvinMedia** [comment]
> Which foreman version are you using? 2.0 or 1.4.1 which is very old!...Which plugin version ? Could you send your logs contaning the error?

I use Foreman 1.4.1 and Foreman 2.0 the same bug in both.

**Comment by tristanrobert** [comment]
Sorry but I need more informations in order to reproduce your error and find your exact scenario: what is the plugin version, logs and/or screenshots,

**Comment by techy2493** [comment]
I'm seeing this error as well on Version 2.1.2 

I see this in a red dialog notification on the top right side of the screen when I attempt to submit a new host. This happens when I am missing required information such as details about the a nic.

**Comment by techy2493** [comment]
I was also seeing this, I'm trying to re-create it now. I believe I was missing some configuration when I was getting this but I don't recall exactly what it was.

**Comment by techy2493** [comment]
![image](https://user-images.githubusercontent.com/2701534/94087741-2b536080-fdd4-11ea-87a6-cd7e64ba3d78.png)

**Comment by techy2493** [comment]
This was still occuring when I went back to Administer > About > Compute Resource > Proxmox > Virtual Machines > Start a VM...

The same occurs when I turn off a VM.

Foreman Version 2.1.2

**Comment by techy2493** [comment]
However, the system appears to work as VMs turn on and off, it appears it's likely trying to parse some sort of response that's changed?
