### ISSUE TITLE
REQ: Add --purge to VM deletion

### ISSUE THREAD

**Issue by rm-td** [theforeman/foreman_fog_proxmox#157]
**Is your feature request related to a problem? Please describe.**
Not a problem or bug, a suggestion for future enhancement. Not seen any similar request, however apologies if duplicated.

**Describe the solution you'd like**
Provide some sort of tickbox or similar when deleting a VM to pass the "--purge" option to remove from backup jobs etc. as per proxmox interface.

Command-line equivalant would be "qm destroy <VMID> --purge".

**Describe alternatives you've considered**
Routine manual observation of proxmox server to ensure correct config and nothing left behind works well, this is a suggested enhancement for the foreman plugin.

**Additional context**
qm(1) manual entry gives following, interest is in the --purge option

qm destroy <vmid> [OPTIONS]

       Destroy the vm (also delete all used/owned volumes).

       <vmid>: <integer> (1 - N)
           The (unique) ID of the VM.

       --purge <boolean>
           Remove vmid from backup cron jobs.

       --skiplock <boolean>
           Ignore locks - only root is allowed to use this option.

Thank you for the proxmox plugin!

**Comment by tristanrobert** [comment]
VM deletion is a foreman feature. I cannot modify the foreman UI. You should post an issue in foreman project. You could ask to customize the host deletion with a custom parameter which could depend on compute resource.
