### ISSUE TITLE
ERF42-8295 [Foreman::Exception]: invalid vmid=0 with foreman ansible modules

### ISSUE THREAD

**Issue by FlatKey** [theforeman/foreman_fog_proxmox#160]
**Description**
If I try to create a VM within the foreman ansible modules (theforeman.foreman.host) I got the exception `ERF42-8295 [Foreman::Exception]: invalid vmid=0`.

**Used components**
Foreman 2.1
Foreman_fog_proxmox 0.11.1
Foreman_ansible_modules 1.0.1
Ansible 2.9

**Expected behavior**
It would be nice if the foreman_fog_proxmox plugin determines and uses the next free valid vmid. As an alternative, the vmid can also be specified as a host parameter and these can be read by the plugin.

**Comment by tristanrobert** [comment]
Next_vmid is computed when you use the foreman forms and create a new VM: https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/app/models/foreman_fog_proxmox/proxmox_vm_new.rb#L110
But if you create the VM without these forms, like ansible playbooks, it will not be executed.
So you need an enhancement which is suitable with both forms and ansible playbooks.

**Comment by FlatKey** [comment]
Exactly, that's why I created [theforeman/foreman_fog_proxmox#161](https://github.com/theforeman/foreman_fog_proxmox/pull/161) , in which next_vmid is also used if the vmid is 0. Does it fit?

**Comment by tristanrobert** [comment]
It needs tests. `0` is an invalid `vmid` so this test should be changed: https://github.com/theforeman/foreman_fog_proxmox/blob/c112ba30e275feb8b0694869c9c2f5fdb4507216/test/unit/foreman_fog_proxmox/proxmox_vm_commands_server_create_test.rb#L34 because it should fails.
Another tests should be written. Why `vmid==0`?

**Comment by tristanrobert** [comment]
I have added tests and a specific case `vmid == 0`.

**Comment by FlatKey** [comment]
Thank you for your support with the added feature and test, but it's a littlebit sad that my pull request was not used or time for improvement was given.
