### ISSUE TITLE
Configuration of first network interface missing after adding second interface in compute profile in WebUI

### ISSUE THREAD

**Issue by FlatKey** [theforeman/foreman_fog_proxmox#162]
**Description**
If I configure a second network interface in the compute_profile within the WebUI, the configuration of the first one is missing after submit the change and reopen the configuration. New VMs are created as expected with two network interfaces, so it seems just a display bug.

**Used components**
Foreman 2.1
Foreman_fog_proxmox 0.11.1
Foreman_ansible_modules 1.0.1
Ansible 2.9

**Expected behavior**
All configured network interfaces are displayed in the compute profile within the WebUI and are able to reconfigure them.

**Screenshots**
Before submit configuration changes:
<img width="699" alt="Screen Shot 2020-07-23 at 21 14 40" src="https://user-images.githubusercontent.com/15485817/88330155-46014e80-cd2b-11ea-9aae-f7bc74c85153.png">

After reopen the compute profile configuration:
<img width="699" alt="Screen Shot 2020-07-23 at 21 15 12" src="https://user-images.githubusercontent.com/15485817/88330168-4dc0f300-cd2b-11ea-8407-5578a689042d.png">

**Comment by tristanrobert** [comment]
Duplicates #166
