### ISSUE TITLE
RPM of version 0.12.1 missing from foreman plugin repo

### ISSUE THREAD

**Issue by rm-td** [theforeman/foreman_fog_proxmox#163]
# [TITLE ISSUE]

## Prerequisites

Please check (put an X between the brackets) the following items before posting any issue:

* [X] Have you check that no [issue](https://github.com/tristanrobert/foreman_proxmox/issues) already exists and could match yours?

* [X] Have you read the [contributing code](CONTRIBUTING.md)?

## Description

RPM of version 0.12.1 appears to be missing from at least the following plugin repos

http://yum.theforeman.org/plugins/2.1/el8/x86_64/
http://yum.theforeman.org/plugins/2.1/el7/x86_64/

Only version 0.12.0 seen. Wanted to see bugfix on previously reported and fixed in 0.12.1 issue when importing VMs.

How are the OS rpm's packaged and updated into the repo? Is this manual or automated, and could it be possible to see the 0.12.1 version packaged please.

Thanks for the plugin!

**Comment by tristanrobert** [comment]
Hello. Packages (rpm and deb) are built with a PR to [foreman-packaging repo](https://github.com/theforeman/foreman-packaging). The rpm 0.12.1 is blocked: https://github.com/theforeman/foreman-packaging/pull/5709

**Comment by tristanrobert** [comment]
I have posted an [issue](https://projects.theforeman.org/issues/30821)

**Comment by tristanrobert** [comment]
Fixed in 0.12.4: https://github.com/theforeman/foreman-packaging/pull/5716
