### ISSUE TITLE
Cannot create a VM with an OS of the RancherOS family

### ISSUE THREAD

**Issue by gmalfray** [theforeman/foreman_fog_proxmox#167]
**Describe**

When I want to create a Host with the RancherOS, I get this error message:

```
Unable to save
Failed to create a compute proxmox1 (Proxmox) instance jess-leather.kosmos.fr: ERF42-4140 `[Foreman::Exception]: Operating system family Rancheros is not consistent with l26`
```

Maybe it's the same problem as for #158 

**Used components**
Foreman 2.1.2
Foreman_fog_proxmox v0.12.4
Promox 6.2-10

**Comment by tristanrobert** [comment]
Fixed by PR https://github.com/theforeman/foreman_fog_proxmox/pull/168
