### ISSUE TITLE
Create Host - Required NIC values are not required on form.

### ISSUE THREAD

**Issue by techy2493** [theforeman/foreman_fog_proxmox#169]
**Describe the bug**
Required parameters for creation of VM not required on Create Host Form

Below error is generated.
Failed to create a compute Proxmox VE (Proxmox) instance edith-calcara.techy.local: Expected([200]) <=> Actual(400 Bad Request) excon.error.response :body => "{\"data\":null,\"errors\":{\"net0\":\"invalid format - missing key in comma-separated list property\\n\"}}" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "97" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Thu, 24 Sep 2020 00:24:57 GMT" "Expires" => "Thu, 24 Sep 2020 00:24:57 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => "10.10.10.5" :local_address => "10.10.10.4" :local_port => 39748 :path => "/api2/json/nodes/pve/qemu" :port => 8006 :reason_phrase => "Parameter verification failed." :remote_ip => "10.10.10.5" :status => 400 :status_line => "HTTP/1.1 400 Parameter verification failed.\r\n" 

Server is fresh install of Foreman 2.1.2 
Proxmox PveVersion 6.2-4

**To Reproduce**
1. Create Host as VM and only set domain value on net0 nic.

**Expected behavior**
A form validation error should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/2701534/94087289-fd215100-fdd2-11ea-8213-1ab3f0be1691.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari] Firefox

**Additional context**

**Comment by techy2493** [comment]
This may not be what was going on, I seem to be continuing to get this even if I set every value on the form. Net0 points to the NIC config, but I'm not sure what else. Let me know if there are any other logs or anything I can provide.

**Comment by techy2493** [comment]
Closed in favor of #167

**Comment by techy2493** [comment]
Closed in favor of #166

**Comment by tristanrobert** [comment]
Duplicated with #166
