### ISSUE TITLE
Documentation adjustment

### ISSUE THREAD

**Issue by BloodyIron** [theforeman/foreman_fog_proxmox#171]
Hey Folks, I don't have the access to make this change, so I figured I should point it out.

The first image here: https://github.com/theforeman/foreman_fog_proxmox/blob/master/.github/hosts.md

"Server VM Proxmox config tab:

Create host server"

Refers to an image file that is mis-spelled "sever" not "server", renaming the file in the image folder in this repo should solve it. Otherwise the embedding is broken until done so. Just figured someone should know ;)

Easy win.

**Comment by tristanrobert** [comment]
Fixed in commit: https://github.com/theforeman/foreman_fog_proxmox/commit/780cb90839c18c9d2eb4d408ffce209f1006643e

**Comment by BloodyIron** [comment]
You're welcome @tristanrobert ! I suspected it was just a small human error that got overlooked, hehe ;P
