### ISSUE TITLE
Behaviour in cluster/live migration/host failure, etc?

### ISSUE THREAD

**Issue by BloodyIron** [theforeman/foreman_fog_proxmox#172]
This is more some inquiry/questions than feature request, but perhaps this might warrant feature request stuff.

I am working towards building out Foreman to manage my Proxmox cluster, I have 3 active and 2 dormant nodes in my Proxmox VE Cluster, and 30-40 VMs spread across the 3x active nodes.

1. How does this plugin manage/respond when VMs are live/not migrated from one Proxmox VE host to another?
2. How does this plugin behave when a cluster node fails and is fenced off/goes into recovery/restart, etc?
3. Is there a way to tell a VM to move from one Proxmox VE Cluster node to another? (I'm not seeing it in the documentation).
4. Is there any way to do VM group behaviour, such as, ensuring VMs are on separate nodes, or sometimes on the same node (for local performance gains), etc?
5. What about Proxmox Node upgrades itself? (to newer versions of Proxmox, etc)

I think this plugin looks really awesome, and I'm hoping it can be useful enough to generally warrant me to never have to log back into the Proxmox VE for work.

**Comment by tristanrobert** [comment]
> This is more some inquiry/questions than feature request, but perhaps this might warrant feature request stuff.
> 
> I am working towards building out Foreman to manage my Proxmox cluster, I have 3 active and 2 dormant nodes in my Proxmox VE Cluster, and 30-40 VMs spread across the 3x active nodes.
> 
> 1. How does this plugin manage/respond when VMs are live/not migrated from one Proxmox VE host to another?

I don't understand the question. You can see node in VM details and compute ressource VMs tab.
> 2. How does this plugin behave when a cluster node fails and is fenced off/goes into recovery/restart, etc?

Plugin requests the Proxmox API (REST) and if node does not anwser you will have an HTTP error.
> 3. Is there a way to tell a VM to move from one Proxmox VE Cluster node to another? (I'm not seeing it in the documentation).

You can move a VM from one node to another easily: you select another node in [main options VM fom](https://github.com/theforeman/foreman_fog_proxmox/blob/master/.github/hosts.md) and save it.
> 4. Is there any way to do VM group behaviour, such as, ensuring VMs are on separate nodes, or sometimes on the same node (for local performance gains), etc?

Server groups are a foreman feature. You can associate a server profile form to a group. In this profile you have a VM form where you can select the default node requested.
> 5. What about Proxmox Node upgrades itself? (to newer versions of Proxmox, etc)

This feature request needs to be done in fog-proxmox first: https://github.com/fog/fog-proxmox/issues/15
> 
> I think this plugin looks really awesome, and I'm hoping it can be useful enough to generally warrant me to never have to log back into the Proxmox VE for work.

Thank you @BloodyIron !

**Comment by BloodyIron** [comment]
@tristanrobert Your answer to question # 3 I think answers # 1, whereby if I live migrate a VM from Proxmox's web interface itself (not Foreman) that I think the Node value for the VM gets updated next fact/info pass, yes?

Otherwise, thanks! Bit of a bummer about not managing node upgrades, but would it be a good idea to have Foreman manage the repos that Proxmox nodes use in a cluster? Or not yet?

**Comment by BloodyIron** [comment]
Closed?

**Comment by tristanrobert** [comment]
If you ask for a new feature, you should make a distinct issue in order to easier follow it.
