### ISSUE TITLE
Proxmox Not Showing as Compute Provider

### ISSUE THREAD

**Issue by HeroesLament** [theforeman/foreman_fog_proxmox#174]
**Describe the bug**

**To Reproduce**
1. Install packages via "yum install tfm-rubygem-fog-proxmox.noarch tfm-rubygem-fog-proxmox-doc.noarch -y"
2. Go to "About -> Available Providers"
3. Proxmox Not Listed

**Expected behavior**
Proxmox should be listed

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave Browser 
 - Version [e.g. 22] Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)

**Yum Output of Package Info**
[root@the-foreman ~]# yum info tfm-rubygem-fog-proxmox.noarch tfm-rubygem-fog-proxmox-doc.noarch
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.gigenet.com
 * centos-sclo-rh: mirror.sjc02.svwh.net
 * centos-sclo-sclo: repos-tx.psychz.net
 * epel: dfw.mirror.rackspace.com
 * extras: mirror.cs.uwp.edu
 * updates: mirrors.umflint.edu
Installed Packages
Name        : tfm-rubygem-fog-proxmox
Arch        : noarch
Version     : 0.12.0
Release     : 1.el7
Size        : 244 k
Repo        : installed
From repo   : /tfm-rubygem-fog-proxmox-0.12.0-1.el7.noarch
Summary     : Module for the 'Fog' gem to support Proxmox VE
URL         : https://github.com/fog/fog-proxmox
License     : GPLv3
Description : This library can be used as a module for `fog`.

Name        : tfm-rubygem-fog-proxmox-doc
Arch        : noarch
Version     : 0.12.0
Release     : 1.el7
Size        : 4.3 M
Repo        : installed
From repo   : foreman-plugins
Summary     : Documentation for rubygem-fog-proxmox
URL         : https://github.com/fog/fog-proxmox
License     : GPLv3
Description : Documentation for rubygem-fog-proxmox.

[root@the-foreman ~]#

**Comment by tristanrobert** [comment]
Hello. You should install the [rubygem-foreman_fog_proxmox](http://37.61.204.219/theforeman/yum/plugins/nightly/el7/x86_64/tfm-rubygem-foreman_fog_proxmox-0.12.4-1.fm2_3.el7.noarch.rpm) plugin.

**Comment by HeroesLament** [comment]
Hi Tristan,

Upon trying to install that plugin, it seems to have an incorrect dependency in the package, see this:

epel/x86_64/metalink                                     | 8.5 kB     00:00
 * base: mirrors.mit.edu
 * centos-sclo-rh: mirror.hostduplex.com
 * centos-sclo-sclo: linux-mirrors.fnal.gov
 * epel: dfw.mirror.rackspace.com
 * extras: centos.mirror.lstn.net
 * updates: mirrors.raystedman.org
ansible-runner                                           | 2.9 kB     00:00
base                                                     | 3.6 kB     00:00
centos-sclo-rh                                           | 3.0 kB     00:00
centos-sclo-sclo                                         | 3.0 kB     00:00
epel                                                     | 4.7 kB     00:00
extras                                                   | 2.9 kB     00:00
foreman                                                  | 2.9 kB     00:00
foreman-plugins                                          | 2.9 kB     00:00
puppet6                                                  | 2.5 kB     00:00
updates                                                  | 2.9 kB     00:00
(1/2): epel/x86_64/updateinfo                              | 1.0 MB   00:05
(2/2): epel/x86_64/primary_db                              | 6.9 MB   00:05
--> Finished Dependency Resolution
**Error: Package: tfm-rubygem-foreman_fog_proxmox-0.12.4-1.fm2_3.el7.noarch (/tfm-                                                                                                                                                                                               rubygem-foreman_fog_proxmox-0.12.4-1.fm2_3.el7.noarch)**
           **Requires: tfm-rubygem(fog-proxmox) >= 0.13**
           Installed: tfm-rubygem-fog-proxmox-0.12.0-1.el7.noarch (@/tfm-rubygem                                                                                                                                                                                               -fog-proxmox-0.12.0-1.el7.noarch)
               tfm-rubygem(fog-proxmox) = 0.12.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@the-foreman ~]#

**Comment by tristanrobert** [comment]
plugin is here: http://koji.katello.org/kojifiles/packages/tfm-rubygem-foreman_fog_proxmox/0.12.4/1.fm2_3.el7/noarch/tfm-rubygem-foreman_fog_proxmox-0.12.4-1.fm2_3.el7.noarch.rpm
and its fog-proxmox dependency is here: http://koji.katello.org/kojifiles/packages/tfm-rubygem-fog-proxmox/0.13.0/1.el7/noarch/tfm-rubygem-fog-proxmox-0.13.0-1.el7.noarch.rpm

Build was successfull here: http://koji.katello.org/koji/buildinfo?buildID=61023

Maybe you should first uninstall tfm-rubygem-fog-proxmox-0.12.0-1.el7.noarch

**Comment by HeroesLament** [comment]
Awesome, that seemed to do it! All the guides I had seen regarding the plugin didn't mention the katello repo. I might just write up a new blogpost for installing the newest version of the plugin :) Thanks Tristan!
