### ISSUE TITLE
Can't get the local storage of my hypervisor when creating a host

### ISSUE THREAD

**Issue by claneys** [theforeman/foreman_fog_proxmox#175]
**Describe the bug**
I'm on Foreman 2.2 (foreman-2.2.0-0.31.rc3.el8.noarch) and use the latest version of the proxmox plugin 0.12.4.
Our Foreman instance has several proxmox compute resources set, 6 for the moment with 3 independents and 3 in the same cluster. When I try to create a host deploying on the cluster of 3 nodes, I want to configure the CD-ROM device to use an ISO from the local storage of the node, but when I select the local storage I see the ISO available from our first compute resource in the list which is not the good one and is even not in the proxmox cluster configuration wanted. It is a completely other proxmox instance on a separate network.

**To Reproduce**
1. Create several proxmox compute resources
2. Try to create a VM
3. Select a node other than the first declared one
4. See ISO from local storage that are not corresponding to the selected node on which the VM would be deployed.

**Expected behavior**
Should list the ISO of the selected proxmox node instead of the first of the list configured in Foreman.

**Comment by tristanrobert** [comment]
When you select a node, the storages lists (disks and cdrom images) are refreshed by this [ajax function](https://github.com/theforeman/foreman_fog_proxmox/blob/2b10be5b1931fa3798a3a6d3bcfb2395f72eca1a/app/assets/javascripts/foreman_fog_proxmox/proxmox_vm.js#L100).
