### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by sbernhard** [theforeman/foreman_fog_proxmox#178]
Hi,

is there a new release planned? What should be done till a new release can be created? How can we help?

Best regards,
Bernhard

**Comment by tristanrobert** [comment]
Hello, as you can see in https://github.com/theforeman/foreman_fog_proxmox/projects and https://github.com/fog/fog-proxmox/projects. I am working on 0.14 which should be an important release. In few days it should be delivered.

**Comment by sbernhard** [comment]
This is great. Thanks for sharing the links.

**Comment by sbernhard** [comment]
It is not yet delivered. Can we somehow help you?
