### ISSUE TITLE
A can't select an Image when creating a compute profile

### ISSUE THREAD

**Issue by MichaelTrip** [theforeman/foreman_fog_proxmox#179]
**Describe the bug**
A can't select an Image when creating a compute profile

**To Reproduce**
1. Go To Compute profiles
2. Create new profile
3. Select proxmox host
4. Image list can't be selected.

**Screenshots**

created image:

![Screenshot at 2020-11-25 13-02-24](https://user-images.githubusercontent.com/1826203/100225574-b361fd80-2f1e-11eb-8b3f-a5b566371f84.png)

This is a cloud init template that i created. 

![Screenshot at 2020-11-25 13-03-02](https://user-images.githubusercontent.com/1826203/100225614-c2e14680-2f1e-11eb-9639-bb5e884020e3.png)

As you can see here the Image dropdown menu is greyed out.

**Used versions**
```
tfm-rubygem-fog-proxmox-0.13.0-1.el7.noarch
tfm-rubygem-foreman_fog_proxmox-0.11.1-1.fm2_2.el7.noarch
foreman-release-2.2.1-1.el7.noarch
katello-3.17.0-1.el7.noarch
```

**Comment by tristanrobert** [comment]
In proxmox when you want to create a vm from a template (image) you must clone it. In foreman, when you want to create a host from an image you use OS tab "Image based" selected and you can not use a profile. This is the way Foreman do it. You can read the [doc](https://github.com/theforeman/foreman_fog_proxmox/blob/master/.github/hosts.md#clone-images)

**Comment by MichaelTrip** [comment]
Thank you for your answer Tristan!
