### ISSUE TITLE
Proxmox kvm console wont start

### ISSUE THREAD

**Issue by aristella** [theforeman/foreman_fog_proxmox#195]
Console for proxmox VM won't start with the following error:

  *Failed to set console: one hash required*

## Environment
Debian 10
Foreman 2.3.3
proxmox-fog 0.12.4
Tested on proxmox 6.3.2 6.3.4 and 6.3.6

**Comment by ahoiroman** [comment]
Same here

## Environment:

Debian 10.9
Foreman 2.4
foreman_fog_proxmox 0.13.3
Proxmox: 6.3-6

**Comment by tristanrobert** [comment]
Difficult to reproduce because of secured websocket with TLS.

**Comment by stdevel** [comment]
Are there any news on this? Problem still seems to exist.

## Environment

- AlmaLinux 8.8
- Foreman 3.7.0
- Katello 4.9.1
- `rubygem-foreman_fog_proxmox-0.14.2-1.fm3_7.el8.noarch` and `rubygem-fog-proxmox-0.15.0-1.el8.noarch`
- Proxmox 8.0.4

**Comment by stdevel** [comment]
Hi there,
the problem still seems to exist - are there news?

# Environment

- AlmaLinux 9.7
- Foreman 3.19
- Katello 4.21
- `rubygem-foreman_fog_proxmox-0.24.0-1.fm3_19.el9.noarch` and `rubygem-fog-proxmox-0.16.0-1.el9.noarch`
- Proxmox 9.2.3
