### ISSUE TITLE
Could not locate Gemfile

### ISSUE THREAD

**Issue by Niemand112233** [theforeman/foreman_fog_proxmox#202]
Hi,
after executing "sudo -u foreman /usr/bin/foreman-ruby /usr/bin/bundle install"

I get this error: Could not locate Gemfile

What's wrong?

**Comment by tristanrobert** [comment]
Hello. You need to create it first: `config\Gemfile.rb` see Readme.

**Comment by Niemand112233** [comment]
with this line: echo "gem 'foreman_fog_proxmox'" | sudo -u foreman tee /usr/share/foreman/bundler.d/Gemfile.local.rb  ?
If yes: I executed this line. This error still appears.

**Comment by Niemand112233** [comment]
Push

**Comment by Niemand112233** [comment]
Noone??

**Comment by tristanrobert** [comment]
Unless you want to contribute to code and test locally, you should install with [OS packages](https://github.com/theforeman/foreman_fog_proxmox#from-os-packages).

**Comment by ekohl** [comment]
OS packages are the supported path.
