### ISSUE TITLE
Associate Vms button not working

### ISSUE THREAD

**Issue by santachago** [theforeman/foreman_fog_proxmox#204]
**Describe the bug**
The associate VMs button on the compute resource is not working, its not able to find VMs to associate with hosts. There is no error reported on the foreman log.

**To Reproduce**
1. Create a new vm on foreman using proxmox as compute resource
2. Go to the host on foreman and disassociate it
3. Go to Compute resources, select the proxmox cluster and then click on the Associate VMs button.
4. the message "No VMs matched any host."

**Expected behavior**
The Host is associated back with the VM

**Versions:**
 - OS: Ubuntu 18.04
 - Foreman: 2.4.0
 - foreman_fog_proxmox: 0.13.3

**Comment by keslerm** [comment]
I think it's related to #203 as well

**Comment by santachago** [comment]
yes i think this is all related to the change of the UUID to add the cluster ID
