### ISSUE TITLE
Foreman Fog Proxmox jenkins AccessPermissionsTest fails 

### ISSUE THREAD

**Issue by Manisha15** [theforeman/foreman_fog_proxmox#208]
**Describe the bug**
Jenkins tests for Access Permissions fail for `[:ostemplates_by_id_and_node_and_storage, :isos_by_id_and_node_and_storage, :ostemplates_by_id_and_node, :isos_by_id_and_node, :storages_by_id_and_node, :iso_storages_by_id_and_node, :bridges_by_id_and_node]`

Run jenkins test on github. For example, https://ci.theforeman.org/job/foreman_bootdisk-pull-request/166/database=postgresql,label=fast,ruby=2.5/testReport/

**Expected behavior**
All tests should be green.

**Actual Behaviour**
AccessPermission tests fail with following error:
`permission for foreman_fog_proxmox/compute_resources/iso_storages_by_id_and_node not found, check access_permissions.rb.
Expected [] to not be empty. (Minitest::Assertion)
/home/jenkins/workspace/foreman_bootdisk-pull-request/database/postgresql/label/fast/ruby/2.5/foreman/test/unit/shared/access_permissions_test_base.rb:29 `

**Additional Information**
test_plugin_helper might be missing libraries and other setups:
`require 'webmock/minitest'`
`require 'webmock'`

**Comment by tristanrobert** [comment]
You should ask foreman core team in community site or with an issue on their redmine site. I have defined these permissions in [engine](https://github.com/theforeman/foreman_fog_proxmox/commit/332ee5a6615ae90f9e627c8db8f3a153b669350e) file. But plugin [access_permissions seeds](https://github.com/theforeman/foreman/blob/develop/db/seeds.d/020-permissions_list.rb) are missing to the tests. They could help on how to fix it.

**Comment by Manisha15** [comment]
Fixed
