### ISSUE TITLE
Not working with Proxmox 7.1 

### ISSUE THREAD

**Issue by TheBadalaMaster** [theforeman/foreman_fog_proxmox#219]
Hello, i'm trying to install this plugin to manage my proxmox server:

When trying to list the machines i get: There was an error listing VMs: 500 Internal Server Error
and "associate vms" returns:  Oops, we're sorry but something went wrong no implicit conversion of Integer into String

root@eric:~#  foreman-rake errors:fetch_log request_id=0c5a3af1
2021-12-19T05:38:24 [I|app|0c5a3af1] Started PUT "/compute_resources/1-Aegon/associate?compute_resource_id=1-Aegon" for 45.173.12.90 at 2021-12-19 05:38:24 +0000
2021-12-19T05:38:24 [I|app|0c5a3af1] Processing by ComputeResourcesController#associate as HTML
2021-12-19T05:38:24 [I|app|0c5a3af1]   Parameters: {"authenticity_token"=>"d4sCh0+hsAURBTX0DPH0+u8aDuOEqjO2NMhTa83lwGX/KogtrXPDK6gZYaimyFr2Tbw1lAkwLbYfiJuxmoAZhQ==", "compute_resource_id"=>"1-Aegon", "id"=>"1-Aegon"}
2021-12-19T05:38:25 [W|app|0c5a3af1] no implicit conversion of Integer into String
2021-12-19T05:38:25 [I|app|0c5a3af1] Backtrace for 'no implicit conversion of Integer into String' error (TypeError): no implicit conversion of Integer into String
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/concerns/host_ext/proxmox/for_vm.rb:27:in `+'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/concerns/host_ext/proxmox/for_vm.rb:27:in `for_vm_uuid'
 0c5a3af1 | /usr/share/foreman/app/models/host.rb:15:in `method_missing'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/services/concerns/foreman_fog_proxmox/compute_resource_host_associator.rb:29:in `block in associate_hosts'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `block in each'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `each'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `each'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/services/concerns/foreman_fog_proxmox/compute_resource_host_associator.rb:28:in `associate_hosts'
 0c5a3af1 | /usr/share/foreman/app/controllers/compute_resources_controller.rb:52:in `associate'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-dsl-2.4.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.19/lib/apipie/static_dispatcher.rb:66:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.19/lib/apipie/extractor/recorder.rb:137:in `call'
 0c5a3af1 | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 0c5a3af1 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.19/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 0c5a3af1 | /usr/share/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 0c5a3af1 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/sprockets-rails-3.4.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 0c5a3af1 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/secure_headers-6.3.3/lib/secure_headers/middleware.rb:11:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/configuration.rb:249:in `call'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/server.rb:447:in `process_client'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 0c5a3af1 | /usr/share/foreman/vendor/ruby/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2021-12-19T05:38:25 [I|app|0c5a3af1]   Rendering common/500.html.erb within layouts/application
2021-12-19T05:38:25 [I|app|0c5a3af1]   Rendered common/500.html.erb within layouts/application (Duration: 4.2ms | Allocations: 5135)
2021-12-19T05:38:25 [I|app|0c5a3af1]   Rendered layouts/_application_content.html.erb (Duration: 2.1ms | Allocations: 4798)
2021-12-19T05:38:25 [I|app|0c5a3af1]   Rendering layouts/base.html.erb
2021-12-19T05:38:25 [I|app|0c5a3af1]   Rendered layouts/base.html.erb (Duration: 4.5ms | Allocations: 6086)
2021-12-19T05:38:25 [I|app|0c5a3af1] Completed 500 Internal Server Error in 1352ms (Views: 14.0ms | ActiveRecord: 2.4ms | Allocations: 190370)

Foreman version: 3.1.0
Plugins: 
 - foreman_fog_proxmox 0.14.0
 - foreman_puppet 2.0.0
root@eric:~#

**Comment by elelayan** [comment]
See #220 for a fix to the error listing VMs. Patching the code in place worked for me
