### ISSUE TITLE
Cannot link existing hosts with Proxmox hosts

### ISSUE THREAD

**Issue by Hedius** [theforeman/foreman_fog_proxmox#224]
**Describe the bug**
I've found the following problem while linking an existing host to a VM

The puppet facts store the MAC in lower case.

The proxmox compute resource (this plugin) pulls the MAC in upper case from the Proxmox API (or Proxmox provides it in upper case)

Therefore, it is not possible to link an existing host with a proxmox host. (Since the comparison is case-sensitive)

**I've created a pull request with a quick solution (converting both MACs to lower case before the comparison): #223** 
Furthermore, d30e1c435c2d456b9519bc74b407f6aa89a256e2 (also in the PR) converts the identity (int) to a string to fix a 500 when clicking on the “Associate VMs” button. Similar to #220 

**To Reproduce**
1. Have an existing foreman/puppet host
2. Attempt to associate proxmox hosts with foreman hosts
3. Fails because of the mentioned MAC mismatch.

**Expected behavior**
The check should be case-insensitive

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14820882/157352324-beee5b83-5e58-4b94-acbd-abc13ffe5ed0.png)
![grafik](https://user-images.githubusercontent.com/14820882/157352421-abe921c9-989a-495d-8bc9-03932706af90.png)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - Version 97.0.2

**Additional context**
None

**Comment by debdolph** [comment]
Any progress on this?

**Comment by Hedius** [comment]
> Any progress on this?

For now the only fix is that you manually edit the plugin files on your foreman server: not ideal :)

Hopefully, this plugin gets updated soon :)

**Comment by Hedius** [comment]
Look in the open pull requests. There are two.

**Comment by KipourosV** [comment]
Yeah found it, thanx!

**Comment by tristanrobert** [comment]
fixed with https://github.com/theforeman/foreman_fog_proxmox/pull/223
