### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bk-lg** [theforeman/foreman_fog_proxmox#227]
# Is this project still maintained?

As there is no actual activity in the developement if  this project since july 2021 I want to ask if this project is still mainted by @tristanrobert ?
Do you have no time to maintain this project anymore or need technial support or addtional funding? 
There are multiple issues which are blocking the usage of this plugin and I would like to help to find a way to keep this plugin alive.

This is in no way confronting. I can't demand anyone to do something on an open source project and I'm glad for anyone who contributes. I only want to check what is the state ot this project and if there is any way users could help to keep it going. 

Thanks in advance for the feedback.

**Comment by tristanrobert** [comment]
Yes I try to maintain it. But: I am alone, I am working as a hobby, during my free time. I have few free time (father). I have few sponsors and I thank you them but sure I could'nt live with only that financial revenue. Multiple issues are redundants and come from break changes in theforeman code (especially in react UI), many are not fixed and I have to find complexed workarounds. Some foreman issues are blocking: https://projects.theforeman.org/issues/34715. I do my best.

**Comment by bk-lg** [comment]
@tristanrobert Thank you for your feedback. Your family is definitly a more important part of your live.
Also thanks for the insight, what it makes so complicate to fix some of this things.

**Comment by gmalfray** [comment]
Thank you Tristan for your work. This plugin works very well for me in the current state so I will no longer update foreman or proxmox ^^

**Comment by djken09** [comment]
@gmalfray can you please detail your setup? I would like to have mine working but so far no luck with diff versions I have tried. Thanks!

**Comment by NausX** [comment]
Hi! I was wondering, have this been tested with foreman 3.3?

**Comment by ekohl** [comment]
> if there is any way users could help to keep it going.

Note that from the Foreman organization we can add additional maintainers. If anyone is interested, please let us know. As an open source project we rely on contributors to help.

I've just merged the open PRs.

@tristanrobert can you add the Foreman org as an owner to https://rubygems.org/gems/foreman_fog_proxmox so we can also do releases? I've emailed the exact instructions.

**Comment by dmgeurts** [comment]
> Hi! I was wondering, have this been tested with foreman 3.3?

Wondering the same but about v3.4. Proxmox came up in a conversation today, so I'm trying to assess how viable a Proxmox integration into Foreman currently is.

**Comment by ekohl** [comment]
Thanks @tristanrobert or adding Foreman to the gem owners. This means we can do a release.

@dmgeurts I can at least do a 0.14.1 bugfix release with the changes since 0.14.0 but I don't have access to a Proxmox setup to verify it really works. Looking at the open issues it may be broken. It'd be good to get some contributions on this plugin.

**Comment by jacac** [comment]
I'm using it with Foreman 3.3 to deploy LXC containers.
![image](https://user-images.githubusercontent.com/422293/202512720-ca428950-85a3-411e-936b-a2a4a6925452.png)
 It is possible to use it but you need to find your ways around some issues.

**Those commits were applied manually:**
https://github.com/theforeman/foreman_fog_proxmox/commit/4e3023c4f11bb35c6e13ec2cc29d07bfa93e41fb
https://github.com/theforeman/foreman_fog_proxmox/commit/a3fd60adad7b98212ea8432b57ba86b77cf5430d
https://github.com/theforeman/foreman_fog_proxmox/commit/fdad87fd9d2c1a894f7affc1fc1c0454070caac2
https://github.com/theforeman/foreman_fog_proxmox/commit/b07947166c068a5f721caf6858c82bf821fe9b51

**Current issues I observed:**
- https://github.com/theforeman/foreman_fog_proxmox/issues/207
  Thanks to @donywahlberg for finding a workaround. [(https://github.com/donywahlberg))](https://github.com/theforeman/foreman_fog_proxmox/issues/207#issuecomment-1060057530)](https://github.com/theforeman/foreman_fog_proxmox/issues/207#issuecomment-1060057530)

- https://github.com/theforeman/foreman_fog_proxmox/issues/228
  A lot of count and byte fields are hit in miss. For example if the VLAN field is converted to a count field (up/down arrows in the input field) the VLAN id will not be transmitted and need to be set manually in Proxmox. Sometimes the VLAN is just a text field and works. The storage size field is sometime not converted to a `byte_size_f ` field and needs the value in bytes. This issues is related to https://github.com/theforeman/foreman/pull/8413#issuecomment-952060517 Another comment on that https://github.com/theforeman/foreman_fog_proxmox/issues/207#issuecomment-1304282909

Those are the ones related to both LXC and VM machines I think. They are some other issues with workarounds just for LXC containers. I cannot speak to the VM side.
