### ISSUE TITLE
VLAN Tag is not transmitted to the proxmox api at vm creation

### ISSUE THREAD

**Issue by ptrktws** [theforeman/foreman_fog_proxmox#228]
**Describe the bug**
If you configure a network interface the "NIC" section is showing a "Tag" Field for VLAN ID, but there is no usage, since it is not saved or used in vm creation

**Expected behavior**
The VLAN Tag should be still present after reopen the interface configuration and should be transmitted as well. 

**Screenshots**
From Logs: 
2022-06-15T11:53:19 [I|app|9ee226ba] Processing by HostsController#interfaces as */*
2022-06-15T11:53:19 [I|app|9ee226ba]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"***", "host"=>{"name"=>"pete-gruba", "organization_id"=>"1", "location_id"=>"2", "hostgroup_id"=>"", "compute_resource_id"=>"2", "puppet_attr
ibutes"=>{"environment_id"=>""}, "puppet_proxy_id"=>"", "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attribute
s"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"", "identifier"=>"", "name"=>"pete-gruba", "domain_id"=>"", "ip"=>"", "ip6"=>"", "managed"=>"1",
"primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "compute_attributes"=>{"type"=>"qemu", "node_id"=>"****", "start_after
_create"=>"0", "pool"=>"", "config_attributes"=>{"description"=>"", "boot"=>"", "onboot"=>"0", "agent"=>"0", "kvm"=>"0", "vga"=>"std", "scsihw"=>"virtio-scsi
-pci", "bios"=>"seabios", "cpu_type"=>"kvm64", "numa"=>"0", "spectre"=>"0", "pcid"=>"0", "ssbd"=>"0", "ibpb"=>"0", "virt_ssbd"=>"0", "amd_ssbd"=>"0", "amd_no
_ssb"=>"0", "md_clear"=>"0", "pdpe1gb"=>"0", "hv_tlbflush"=>"0", "aes"=>"0", "hv_evmcs"=>"0", "ostype"=>"l26"}, "volumes_attributes"=>{"0"=>{"_delete"=>"", "
storage_type"=>"hard_disk", "storage"=>"NFS_DATASTORE", "controller"=>"virtio", "device"=>"0", "cache"=>"", "size"=>"8589934592", "id"=>"virtio0"}, "1"=>{"id
"=>"rootfs"}}}, "architecture_id"=>"", "operatingsystem_id"=>"", "provision_method"=>"build", "build"=>"1", "medium_id"=>"", "ptable_id"=>"", "disk"=>"", "ro
ot_pass"=>"[FILTERED]", "is_owned_by"=>"4-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "fakepassword"=>"[FILTERED]"}

**Additional context**
I am using the latest plugin with the latest proxmox installation. Since there are a some issues, maybe someone faced this one and knows a workaround?

**Comment by jacac** [comment]
It seems to me that the `counter_f` fields are not working. The interface modal pushes those values to a hidden input field and all `counter_f` fields are not populating. Another interesting aspect is that those `counter_f` fields are changed to a `foreman-react-component`. Maybe it has something to do with that.

When I change those `counter_f` to `text_f` in those files, the VLAN tag get send again. I'm not sure if it would be the right approach but maybe someone can tell me what needs to be done instead.

https://github.com/theforeman/foreman_fog_proxmox/blob/4e3023c4f11bb35c6e13ec2cc29d07bfa93e41fb/app/views/compute_resources_vms/form/proxmox/server/_network.html.erb#L25
https://github.com/theforeman/foreman_fog_proxmox/blob/4e3023c4f11bb35c6e13ec2cc29d07bfa93e41fb/app/views/compute_resources_vms/form/proxmox/container/_network.html.erb#L30

@ezr-ondrej  Could you tell us what needs to be done to fix this or to whom we can talk to get some guidance? I could get the PR ready if switching from `counter_f` to `text_f` is the right approach.

**Comment by tristanrobert** [comment]
This issue is related to #207 because fieldsets enabling or disabling does not work with counter_f and byte_size_f which are react components nested in divs
