### ISSUE TITLE
Host deletion does not delete vm on proxmox

### ISSUE THREAD

**Issue by tristanrobert** [theforeman/foreman_fog_proxmox#230]
Proxmox 7.1
Foreman 3.4
Foreman_fog_proxmox 0.14.0

**Comment by tristanrobert** [comment]
If you want to delete vm on host destroy, add this line in config/settings.yml:

```yml
:destroy_vm_on_host_delete: true
```

**Comment by ekohl** [comment]
Note there is also a setting in the UI you can change. No need to modify the YAML file.

**Comment by tristanrobert** [comment]
> Note there is also a setting in the UI you can change. No need to modify the YAML file.

Thank you !
