### ISSUE TITLE
Version 0.14.2 not available on Foreman repo

### ISSUE THREAD

**Issue by ijonjic11** [theforeman/foreman_fog_proxmox#250]
Hi to all,

i'm wondering when the latest version (with fix for issue #207 and others) will be available to install from foreman's official repo or is there 
a way to update the current version that can be installed from repo(0.14.0 --> 0.14.2).

**Comment by tristanrobert** [comment]
Hello. You can use the gem install while waiting for the OS package (deb or rpm) to be available.

**Comment by ekohl** [comment]
FYI: we do have a few PRs open for that:
* https://github.com/theforeman/foreman-packaging/pull/9084
* https://github.com/theforeman/foreman-packaging/pull/8859
* https://github.com/theforeman/foreman-packaging/pull/8850

I'll wrap those up, but any help around that would be appreciated. We're an open source project and rely on contributors. If you rely on this plugin, we welcome new contributors.

**Comment by Manisha15** [comment]
Closing the issue as the version is now available on foreman repo.
