### ISSUE TITLE
vmid not auto set when creating from Foreman API

### ISSUE THREAD

**Issue by EddMCambs** [theforeman/foreman_fog_proxmox#254]
**Describe the Bug**
Creating hosts through the web ui works correctly, however attempting to do it through the api returns the error `Backtrace for 'Action failed' error (ArgumentError): vmid is required for this operation`

**To Reproduce**
Attempt to create a host through the API with a host group that defines using a proxmox compute resource. Sample python used:
```
import requests, json
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
retry_strategy = Retry(
    total=5,
    status_forcelist=[429, 502, 503, 504],
    allowed_methods=["POST","GET"],
    backoff_factor=10
)
adapter = HTTPAdapter(max_retries=retry_strategy)
forehttp = requests.Session()
forehttp.auth = ("<foremanusername>","<foremanPAT>")
forehttp.mount('https://', adapter)
create_params={
    'host':{
        'name': <hostname>,
        'hostgroup_id': 28, # Host group that is set to use a proxmox compute profile
        'location_id': 5,
        'organization_id': 3,
        'build': True,
        'compute_attributes': {
            'start': 1,
           # 'vmid': '123'
        }
    }
}
r = forehttp.post("<foremanurl>/api/hosts",data=json.dumps(create_params),headers={'Content-Type': 'application/json'})
r.raise_for_status()
```

**Expected behavior**
As with the webui, the plugin should get the next vmid automatically. 

**Additional context**
If a valid VMID is specified manually (by uncommenting the `'vmid': 123` under `compute_attributes`) it works perfectly, but that is not easily workable for this script. Additionally passing any string to `vmid` that isn't a valid proxmox vmid results in the host being created in foreman, but silently failing to do anything in proxmox. Subsequent efforts to edit the VM  in foreman will return the error 
```
'<hostname>' not found on '<proxmox cluster>(Proxmox)' '<hostname>' could be deleted or '<proxmox cluster> (Proxmox)' is not responding.
```

**Versions**
Foreman: 3.6.1
rubygem-fog-proxmox.noarch: 0.15.0-1.el8
rubygem-foreman_fog_proxmox.noarch: 0.14.2-1.fm3_7.el8

**Comment by maximiliankolb** [comment]
I ran into the same issue when trying to provision a host on Promox using Hammer CLI:

````
Could not create the host:
  Failed to create a compute Proxmox (Proxmox) instance host.example.com: vmid is required for this operation
````
