### ISSUE TITLE
Proxmox's Compute Resources Does not Retrieve VMs

### ISSUE THREAD

**Issue by djken09** [theforeman/foreman_fog_proxmox#258]
**Describe the bug**
Proxmox's Compute Resources Does not Retrieve VMs after been created. It returns "_There was an error listing VMs: 500 Internal Server Error_"
It also failed while trying to manually associate a VM (logs provided below)

**To Reproduce**
1. Go to Compute Resources -> Select a Compute Resources -> Virtual Machines Tab
2. Error: "_There was an error listing VMs: 500 Internal Server Error_"

**Expected behavior**
Virtual Machines should be shown on the Virtual Machines Tab

**Screenshots**
![image](https://user-images.githubusercontent.com/105390858/235452488-d1796c09-6036-4c08-beff-0679111d9559.png)
![image](https://user-images.githubusercontent.com/105390858/235452558-3e1ff5f9-8ada-41b7-8969-5fd8dfe73f3e.png)

**Env Versions:**
 - Proxmox 7.4.3
 - Foreman version 3.1.3
 - foreman_fog_proxmox 0.14.0
 - foreman_puppet 2.0.7
 - ruby2.7

**Additional context**
See logs below.
`foreman-rake errors:fetch_log request_id=21ac4afe
2023-05-01T12:37:54 [I|app|21ac4afe] Started PUT "/compute_resources/1-pve01/associate?compute_resource_id=1-pve01" for 192.168.1.10 at 2023-05-01 12:37:54 +0000
2023-05-01T12:37:54 [I|app|21ac4afe] Processing by ComputeResourcesController#associate as HTML
2023-05-01T12:37:54 [I|app|21ac4afe]   Parameters: {"authenticity_token"=>"d+nytzVyfptA9grke5IXe9NRyt4XcU12NZCW15U3hSSnmO6Bgdg10JozeAwD56gKqi+RzPs/uoSVwLTFuAtKAw==", "compute_resource_id"=>"1-pve01", "id"=>"1-pve01"}
2023-05-01T12:37:54 [W|app|21ac4afe] undefined method `first' for nil:NilClass
2023-05-01T12:37:54 [I|app|21ac4afe] Backtrace for 'undefined method `first' for nil:NilClass' error (NoMethodError): undefined method `first' for nil:NilClass
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/helpers/nic_helper.rb:66:in `extract_nic_id'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server_config.rb:128:in `block in initialize_interfaces'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server_config.rb:125:in `each'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server_config.rb:125:in `initialize_interfaces'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server_config.rb:85:in `initialize'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server.rb:235:in `new'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server.rb:235:in `initialize_config'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/server.rb:69:in `initialize'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:88:in `new'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:88:in `new'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/servers.rb:32:in `new'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/fog-proxmox-0.14.0/lib/fog/proxmox/compute/models/servers.rb:63:in `get'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/proxmox_vm_queries.rb:51:in `block in vms'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/proxmox_vm_queries.rb:51:in `each'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/proxmox_vm_queries.rb:51:in `vms'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.0/app/services/concerns/foreman_fog_proxmox/compute_resource_host_associator.rb:28:in `associate_hosts'
 21ac4afe | /usr/share/foreman/app/controllers/compute_resources_controller.rb:52:in `associate'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-dsl-2.4.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.20/lib/apipie/static_dispatcher.rb:66:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.20/lib/apipie/extractor/recorder.rb:137:in `call'
 21ac4afe | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 21ac4afe | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.20/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 21ac4afe | /usr/share/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 21ac4afe | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 21ac4afe | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/secure_headers-6.3.3/lib/secure_headers/middleware.rb:11:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 21ac4afe | /usr/share/foreman/vendor/ruby/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2023-05-01T12:37:54 [I|app|21ac4afe]   Rendering common/500.html.erb within layouts/application
2023-05-01T12:37:54 [I|app|21ac4afe]   Rendered common/500.html.erb within layouts/application (Duration: 10.6ms | Allocations: 5119)
2023-05-01T12:37:54 [I|app|21ac4afe]   Rendered layouts/_application_content.html.erb (Duration: 5.9ms | Allocations: 4774)
2023-05-01T12:37:54 [I|app|21ac4afe]   Rendering layouts/base.html.erb
2023-05-01T12:37:54 [I|app|21ac4afe]   Rendered layouts/base.html.erb (Duration: 10.8ms | Allocations: 6062)
2023-05-01T12:37:54 [I|app|21ac4afe] Completed 500 Internal Server Error in 627ms (Views: 37.9ms | ActiveRecord: 10.4ms | Allocations: 120830)

Foreman version: 3.1.3
Plugins: 
 - foreman_fog_proxmox 0.14.0
 - foreman_puppet 2.0.7`

**Comment by pdolinic** [comment]
Hi, you are running 0.14.0, this seems to be fixed in the the newer versions and is related to changing a string. 
You can fix this inplace and restart foreman: All you need small changes across 3 files in 2PRs:

1) https://github.com/theforeman/foreman_fog_proxmox/pull/220/files
2) https://github.com/theforeman/foreman_fog_proxmox/pull/223/files

**Comment by djken09** [comment]
Thanks @pdolinic ! Taking a look to those fixes and I will confirm if that fix it.

**Comment by djken09** [comment]
Indeed - confirmed that this issues is fixed on the latest release. Thanks!
