### ISSUE TITLE
foreman_fog_proxmox installed from rpm - doesn't show up

### ISSUE THREAD

**Issue by sentinel159868** [theforeman/foreman_fog_proxmox#57]
Hi Robert,

i've installed your plugin from the foreman 1.20 repository. It installed succesfully, but doesnt show up in the frontend. Also can't i see any errors. 

Is there anything additional to do?

regards
sentinel

OS: CentOS Linux release 7.5.1804
Foreman: 1.20.1

**Comment by quba42** [comment]
Have you done a `katello-service restart`?
If that does not solve your problem try running `foreman-installer` followed by `katello-service restart`.
(I am not 100% sure what combination of steps is sufficient, but we ran both the installer and the service restart which caused the plugin to show up.)

I should also note that we installed `rubygem-foreman_fog_proxmox` from the `rpm/develop` branch in [foreman-packaging](https://github.com/theforeman/foreman-packaging). This package then pulls in the `rubygem-fog-proxmox` package. This latter package is the only package I can see on the `rpm/1.20` branch.

Perhaps the packaging of this plugin just is not ready for foreman 1.20 yet?

**Comment by sentinel159868** [comment]
So... finally... I've been tested every possible workaround. Nothing helped. I can't get it working..... Is there any installation that is working as expected?

**Comment by hlawatschek** [comment]
Hi @sentinel159868 I've got the plugin running and it works as expected. What is your issue?

**Comment by hlawatschek** [comment]
You need to install the rpms tfm-rubygem-fog-proxmox and tfm-rubygem-foreman_fog_proxmox
Then go to Infrastructure -> Compute Resources -> Create Compute Resource 
choose Proxmox and add your connection details...

**Comment by sentinel159868** [comment]
Exactly this is what i've done. I can see the Proxmox as ressource type. But when i fill in the form the "node" select doesn't provide any entries (but i can the the http request on the Proxmox node itself)

**Comment by sentinel159868** [comment]
![image](https://user-images.githubusercontent.com/22539551/50602016-5edeb080-0eb6-11e9-8ab6-1391a023b7bf.png)

**Comment by sentinel159868** [comment]
I got it. It was the password :-D (too long and with brackets)

**Comment by martan3d** [comment]
I have gotten the plugin to install and see the above screen, however the node is blank. We have a proxmox instance with about 30 VMs.

**Comment by tristanrobert** [comment]
The plugin has been tested only with Proxmox >=5

**Comment by martan3d** [comment]
Ok, I have spun up an instance of Proxmox 5.3-5. I am still not seeing anything in the 'node' parameter.  What certificate should I use? The pve-ssl.pem from proxmox?  Does this make a difference?  I try to unclick the 'SSL verify peer' but it doesn't seem to do anything.

**Comment by sentinel159868** [comment]
Hi martan.
on which OS, Ruby and Foreman version are you?

**Comment by martan3d** [comment]
Centos 7.5.1804, running on a VM.  I installed the latest Foreman (1.20.1) using the 'install foreman' quick start method.  I have Ruby 2.5.3.  I installed the latest plugin rpms from here:
https://yum.theforeman.org/plugins/nightly/el7/x86_64/
tfm-rubygem-fog-proxmox-0.5.3-1.el7.noarch.rpm
fm-rubygem-foreman_fog_proxmox-0.5.3-1.fm1_21.el7.noarch.rpm

I can see the plugin, but the Node box is empty.  I was expecting to see the pve node in there. As mentioned I have a fresh Proxmox 5.3 I am trying to get it to work with.
Thanks for any help on this.

**Comment by somebears** [comment]
I am having the same issue as martan3d, using the same Versions
I could not find any useful information in logs apart from the foreman call itself (production.log)
`2019-01-11T13:31:20 [I|app|cae2b]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Mj53CGU3LiRUYMka5QQxaYW08XlxJZvxEplQQt9WrfKRyK2npiWT6MPUU8xAZwegicsS0Qjztao2F3agyjFvPw==", "compute_resource"=>{"name"=>"proxmox_local", "provider"=>"Proxmox", "description"=>"", "url"=>"https://192.168.122.10:8006/api2/json", "user"=>"root@pam", "password"=>"[FILTERED]", "ssl_verify_peer"=>"1", "ssl_certs"=>"-----BEGIN CERTIFICATE-----\r\nMIIEwDCCAqigAwIBAgIBATANBgkqhkiG9w0BAQsFADB2MSQwIgYDVQQDDBtQcm94\r\nbW94IFZpcnR1YWwgRW52aXJvbm1lbnQxLTArBgNVBAsMJGM4MzMwYTJlLWRlMzct\r\nNGI2NS05NzlmLTE0ZmMyZGRhNWQyYjEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFu\r\nYWdlciBDQTAeFw0xOTAxMTAxMDUyMzFaFw0yOTAxMDcxMDUyMzFaMF8xGTAXBgNV\r\nBAsTEFBWRSBDbHVzdGVyIE5vZGUxJDAiBgNVBAoTG1Byb3htb3ggVmlydHVhbCBF\r\nbnZpcm9ubWVudDEcMBoGA1UEAxMTcHZlLnNoLnN5bW1lZGlhLm9yZzCCASIwDQYJ\r\nKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM4BvfM+CzlGtCDXy03v5kMIEJUQm4iQ\r\n0YtbxxGEUQ6WY7qvEB/zuyyY/k8Rxgy97FHVHvCL9CU4OhwgLjRN4pfIQ70cuVrU\r\njv5SIZhiBf4VFQlLMF6QbUTQgGsLqvk1EdMfsQ2VreFD1QmVI3sXROwbbfR7e60r\r\nfrKJEEG2Kx1QebV5VZgYGwoAm/jAB7dT+kTrI6CxxYdg8wxQiwG3iuGq4tjEBPS4\r\nGgNt8x06LhooDUMZjihj+A2NP3o1ok2Ks7/sMGcq4ZYs9VKgXLrvb+Rz6s62EB7R\r\n/WUqJkLNq0/qVvhW2SzE4upkeFv0w5GypDLbwWvp6ola4KpjtaJpyaMCAwEAAaNw\r\nMG4wCQYDVR0TBAIwADATBgNVHSUEDDAKBggrBgEFBQcDATBMBgNVHREERTBDhwR/\r\nAAABhxAAAAAAAAAAAAAAAAAAAAABgglsb2NhbGhvc3SHBMCoegqCA3B2ZYITcHZl\r\nLnNoLnN5bW1lZGlhLm9yZzANBgkqhkiG9w0BAQsFAAOCAgEAkNu4GVzABL62/8w/\r\nZrOT05rra+OM1WyhnxAzHTMQtqBgVFK8AVZ61gcDeSqk8Vo9g4itFWUOeC1mjEyN\r\nN2Uq5oGgZla48iS3vVn8mn/+hJ19/vGC02sBfV+097VluXAD8Cn37LEO5iqivf6R\r\n9i3ShDHMhISdO5U/7eXsUx24czF4dVr3EqPrMirPh/emisv5lRrmrNKMzhafXW++\r\nmTisPsyMtU3hRC8WSz/JiILqwQZjVn48/LlhsMjLb4L6wVmg0aZ9DUAwSzHqFEVh\r\n9qGjAltb0igbxkZ8F/2mRNBD4/bNABf0qdhTAwESXJj0jL+lVYO/wge5Nr751axg\r\nbAhKAgfsLjLRVsWVzzgQs4DQnyKQXKPHUQK6n1kDucmCdAdXffYwtrO2zhVNasRj\r\npHOOHnpK2zuV1R5hh5RYnnw4UkUEH7X605b6QlvwcsTveKm3kl2/xBMFqahxPb1u\r\n2nTdYOaOGha3EXPK4gtlZytn4TETk0o6SZlUwGJkZhhKYKOotAc9K2/HGcM8ufzj\r\nEdInR9cs8zRNUlOuErJRDJPHa9wU+QX4s53IkBX9eUu2PMq5S4V4NhBiB37O5+v9\r\n6c3YIqzdGIuAltQglo9rzYhBJ5R79+KdjDe2t/KvwEQpg2Zg1Y3apvu4QsUdhgGU\r\nM99d0uGzrwoMddbyG3aTlZgvehU=\r\n-----END CERTIFICATE-----", "node_name"=>""}, "commit"=>"Submit"}`

I can't see any call to the proxmox API, although the API itself is reachable and working as far as I can tell.

I had this problem when installing the gem directly aswell, might this be a centos related problem?

**Comment by tristanrobert** [comment]
I can't reproduce your issue. Have you tried with latest version (0.5.5) of the plugin?

**Comment by somebears** [comment]
I have the same problem on v0.5.5
I can reproduce the issue by creating a fresh centOS, changing the hostname + adding it to the hosts file.
Then I install foreman as described in the manual (quickstart) and open ports 8443, 443 and 8140 and finish up by installing tfm-rubygem-fog-proxmox and tfm-rubygem-foreman_fog_proxmox and rebooting the VM

**Comment by Yamakasi** [comment]
My duplicate #60 is also using 0.5.5

**Comment by denz7201** [comment]
Turn off selinux on the foreman server.  The same issue happened to me.

**Comment by Yamakasi** [comment]
@denz7201 that fixed it directly!! Thanks a lot!! (we need to investigate this) @tristanrobert
