### ISSUE TITLE
foreman_fog_proxmox installed from rpm - Not visible

### ISSUE THREAD

**Issue by pietjepuk111** [theforeman/foreman_fog_proxmox#59]
**Describe the bug**
I cant see the proxmox plugin see in the  providers list. I have installed the rpm via repo 

OS: CentOS Linux release 7.5.1804
Foreman: 1.20.1

I have installed the server twice but the list is empty. 

This is what I found in the log files.

  from /usr/share/foreman/Gemfile.in:55

 #  -------------------------------------------
/usr/share/foreman/Gemfile.in:55:in `instance_eval'
/usr/share/foreman/Gemfile.in:55:in `block in eval_gemfile'
/usr/share/foreman/Gemfile.in:54:in `each'
/usr/share/foreman/Gemfile.in:54:in `eval_gemfile'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:47:in `instance_eval'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:47:in `eval_gemfile'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:12:in `evaluate'
/opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/gemfile.rb:46:in `parse'
/opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
/usr/share/foreman/config/application.rb:17:in `<top (required)>'
/usr/share/foreman/Rakefile:1:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
SyntaxError: (eval):1: syntax error, unexpected unary-, expecting keyword_do or '{' or '('
...'foreman_fog_proxmox'" | sudo -u foreman tee /usr/share/fore...
...                              ^
(eval):1: unknown regexp options - har
/usr/share/foreman/Gemfile.in:55:in `instance_eval'
/usr/share/foreman/Gemfile.in:55:in `block in eval_gemfile'
/usr/share/foreman/Gemfile.in:54:in `each'
/usr/share/foreman/Gemfile.in:54:in `eval_gemfile'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:47:in `instance_eval'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:47:in `eval_gemfile'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/dsl.rb:12:in `evaluate'
/opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/gemfile.rb:46:in `parse'
/opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
/usr/share/foreman/config/application.rb:17:in `<top (required)>'
/usr/share/foreman/Rakefile:1:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
[root@spacewalk foreman]#
[root@spacewalk foreman]# cd /usr/share/foreman/Gemf
-bash: cd: /usr/share/foreman/Gemf: No such file or directory

**Comment by pietjepuk111** [comment]
Nobody can help me?

**Comment by tristanrobert** [comment]
I am trying to reproduce your issue. I am working on it.

Le dim. 3 févr. 2019 à 22:04, pietjepuk111 <notifications@github.com> a
écrit :

**Comment by tristanrobert** [comment]
I am trying to reproduce your issue. I am working on it.

**Comment by Yamakasi** [comment]
OK, went back to a 1.20.1 installation with 0.5.5 where the same happens for me.

Ideas are welcome!

**Comment by denz7201** [comment]
In one of the duplicates I commented with my solution
[](url)https://github.com/theforeman/foreman_fog_proxmox/issues/57#issuecomment-462496940

**Comment by pietjepuk111** [comment]
Hi,
This is a work around not a solution. What if we want to use the plugin with selinux on?

**Comment by tristanrobert** [comment]
Hello, you should read this [tutorial](https://projects.theforeman.org/projects/foreman/wiki/SELinux) on how to setup Selinux with Foreman and all its plugins. There is also a [helper](https://github.com/theforeman/foreman-selinux) to apply your policies.

**Comment by pietjepuk111** [comment]
Hi again,
I have disabled selinux and the proxmox plugin is not visible in the gui.
I have tried to disabled the plugin, reboot the server. And tried it again. but with no luck.

**Comment by denz7201** [comment]
This also might help for people struggling with selinux issues. Audit2allow is quite useful.  https://osric.com/chris/accidental-developer/tag/selinux/
