### ISSUE TITLE
Foreman cannot auth against the Proxmox server

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/foreman_fog_proxmox#60]
**Describe the bug**
Foreman cannot auth against the Proxmox server, Test failed following:
https://github.com/tristanrobert/foreman_fog_proxmox/blob/master/.github/compute_resource.md

**To Reproduce**
Follow: https://github.com/tristanrobert/foreman_fog_proxmox/blob/master/.github/compute_resource.md

**Expected behavior**
Get list of the nodes

**Screenshots**
Not available

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser Firefox Developer Edition
 - Version 66.0b3

**Additional context**
Cannot see anything error related in production.log, also not on DEBUG level

**Comment by Yamakasi** [comment]
As this is a bug people seem to be able to use it, is it a selfsigned cert issue maybe ?

**Comment by hlawatschek** [comment]
Have you tried to connect without ssl verification?

**Comment by Yamakasi** [comment]
> 
> 
> Have you tried to connect without ssl verification?

Yes, it selects SSL right away.

**Comment by hlawatschek** [comment]
OK, try to unselect "SSL verify peer" and trigger the "Test Connection" Button. Does this work?

**Comment by Yamakasi** [comment]
> 
> 
> OK, try to unselect "SSL verify peer" and trigger the "Test Connection" Button. Does this work?

No, doesn't work, it gets re-selected after the test ;)

**Comment by Yamakasi** [comment]
@hlawatschek Any update on this ? Added a valid Certificate to Proxmox, still the same issue.

**Comment by Yamakasi** [comment]
OK updating this as I have tested all versions from 1.19 - 1.21 with all versions of this module with no luck against a Proxmox 5.3-8 host.

Myabe there has been changed something on API side of Proxmox ?

**Comment by Yamakasi** [comment]
Extra update:

https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_5.3

> pvesh rewrite to use the new CLI Formatter framework - providing a configurable output format for all > API calls (formats include: json, yaml and a pleasant table output with borders). Provides unified 
> support for json output for the PVE CLI Tools.

Let's assume this is an API issue as someone told me to have it running on FM 1.19 / FOG 0.5.5-2 / PRXMX 5.3.5

**Comment by Yamakasi** [comment]
Fixed in #57 ? or needs further investigation ?

**Comment by tristanrobert** [comment]
It is API changes from Proxmox 5.3. I am working on [it](https://github.com/fog/fog-proxmox/issues/45).
