### ISSUE TITLE
Associate VM's

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/foreman_fog_proxmox#61]
**Is your feature request related to a problem? Please describe.**
I'm not sure how where the VM's you want to associate with the existing hosts in Foreman are refering to. New Hosts are bound to the ID but how is this handled on Associate when the hosts doesn't know the ID of the VM ?

**Describe the solution you'd like**
Associate existing hosts to their existing VM's

**Comment by tristanrobert** [comment]
You should ask your question to Foreman support.
