### ISSUE TITLE
Cannot create VM =>  Invalid identifier interface[0]

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/foreman_fog_proxmox#63]
**Describe the bug**

On creating a Host you get this whent he Network interface is set to 0 or 1, or....

**: ERF42-1306 [Foreman::Exception]: Invalid identifier interface[0]. Must be net[n] with n integer >= 0**

**To Reproduce**
1. Create host
2. Go to interfaces
3. Set: Device Identifier : 0 or 1....
4. Create host

**Expected behavior**
Create the VM

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser Firefox Developer Edition
 - Version 66.0b10

**Comment by tristanrobert** [comment]
You must set net0 or net1 and not 0 or 1.

**Comment by Yamakasi** [comment]
> 
> 
> You must set device with net0 or net1 and not 0 or 1.

Sorry I see now indeed. 

What I always wonder if why the "cache" when a VM creation fails, also on oVirt, is multiplying disks, etc, so somewhat failing on clientside JS ?

**Comment by tristanrobert** [comment]
You should ask your cache question to Foreman and oVirt support.

**Comment by Yamakasi** [comment]
> 
> 
> You should ask your cache question to Foreman and oVirt support.

I will do, oVirt was more as a compute resource reference, same as Proxmox.
