### ISSUE TITLE
Cannot edit submit associated VM

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/foreman_fog_proxmox#65]
**Describe the bug**
It seems it's not possible to submit a associated VM you want to edit. In my opinion it fails on the Network interface and you need to remove the mac-address to be able to submit at least. DHCP seems to fail as it wants to overwrite which it cannot reach that notice because this module also triggers something there.

**To Reproduce**
1. Go to Host
2. Click on Edit
3. Submit

**Expected behavior**
Successful change of the host

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox (all versions)
 - Version All

**Comment by tristanrobert** [comment]
Is your host is associated and managed by Foreman?

**Comment by Yamakasi** [comment]
> 
> 
> Is your host is associated and managed by Foreman?

Yes it was, don't have a test at the moment where I can try on.
