### ISSUE TITLE
Invalid PVE ticket renewal

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#77]
**Is your feature request related to a problem? Please describe.**
Like in the Closed ticket [https://github.com/theforeman/foreman_fog_proxmox/issues/55#](https://github.com/theforeman/foreman_fog_proxmox/issues/55#)
it would be nice to have a automatic ticket renewal mechanism. 

**Describe the solution you'd like**
A soon as the ticket expires, and Proxmox throw the "invalid PVE ticket" exception, plugin should catch this and ask for a new ticket.

**Describe alternatives you've considered**
I have tried pasting the ticket inside compute resource password field, but it did not help. And I think it will only work for another two hours, please correct me if I am wrong about it.

**Comment by Yamakasi** [comment]
I hope to have this seen in 0.8.0

Is it a complex issue ?

**Comment by tristanrobert** [comment]
It is indeed a [Fog-Proxmox bug](https://github.com/fog/fog-proxmox/issues/49).

**Comment by TekunoKage** [comment]
Any hint to workaround this issue, until fix come out? I have PVE 5.4.8 with Foreman 1.22.0 and the plugin 0.8.0 and I'm also confronting the issue.

**Comment by pdzionek** [comment]
> Any hint to workaround this issue, until fix come out? I have PVE 5.4.8 with Foreman 1.22.0 and the plugin 0.8.0 and I'm also confronting the issue.

Are you sure you have version 0.8 ? If yes this problem shouldn't appear. Probably you are facing following problem [https://github.com/theforeman/foreman_fog_proxmox/issues/86](https://github.com/theforeman/foreman_fog_proxmox/issues/86). If so, please follow instructions from my last post.

**Comment by TekunoKage** [comment]
> 
> 
> > Any hint to workaround this issue, until fix come out? I have PVE 5.4.8 with Foreman 1.22.0 and the plugin 0.8.0 and I'm also confronting the issue.
> 
> Are you sure you have version 0.8 ? If yes this problem shouldn't appear. Probably you are facing following problem #86. If so, please follow instructions from my last post.

Well unless there is a bug, on the output on About - System Status - Plugin, the indicated version is 0.8.0.

Anyway the output on the test is similar to the problem #86. Therefore could be that issue, I will go an fallow that threat. I will let you know there.

Thanks,
