### ISSUE TITLE
Additional disk size and device number issue

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#78]
**Describe the bug**
While you are creating a new vm, and you add additional disks it is not possible to change their size and device id with up and down arrows. You can only do it by typing. It doesn't apply to default disk, for which you can use these up/down arrows.

**To Reproduce**
1. Go to 'All Host -> Create Host'
2. While you are on Host Tab, choose deploy on 'Proxmox Node'
3. Switch to 'Virtual Machine tab'
4. Go to disk section and add another disk/disks
5. Try clicking up/down arrows for device id and size

**Expected behavior**
Up and Down arrows should work for added disks

**Screenshots**
![unresponsive1](https://user-images.githubusercontent.com/50098566/56945064-077be480-6b26-11e9-9f03-34c7e98ec016.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04
 - Browser Firefox
 - Version 66.0.3

**Foreman - Proxmox versions**
foreman 1.21.3-1
ruby-foreman-fog-proxmox 0.6.0-1
Proxmox cluster 5.3.7

**Comment by tristanrobert** [comment]
I have tested with 0.7.0 and Foreman 1.22 and 1.23. It is already fixed. The only issue that remains is minimum to 1 and not 0: https://projects.theforeman.org/issues/25111

**Comment by pdzionek** [comment]
Ok, I will check it out, as soon as, foreman releases 1.22 as stable version.

**Comment by tristanrobert** [comment]
But you are right, the spinner still don't work when you just add a disk.

**Comment by m-bucher** [comment]
foreman issue is fixed in 1.24: https://github.com/theforeman/foreman/pull/7057
