### ISSUE TITLE
Unnecessary/Unwanted disk addition on host creation

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#79]
**Describe the bug**
While you are creating a new VM, and you chose your disks, OS, config and if you forget something, which is mandatory, and you click submit, in Virtual Machine section, plugin/form will re-add the default disk. So if you not notice it, you will end up with one not needed disk. One note, it only happens when you change your controller from default one, which is always SCSI (I mentioned this bug here [https://github.com/theforeman/foreman_fog_proxmox/issues/76](https://github.com/theforeman/foreman_fog_proxmox/issues/76) ) 

**To Reproduce**
1. Go to 'All Host -> Create Host'
2. While you are on Host Tab, choose deploy on 'Proxmox Node'
3. Switch to 'Virtual Machine tab'
4. Add some more disks
5. Fill all other fields in whole host creation process, but don't fill root password.
6. Click submit and go back to 'Virtual Machine' tab.

**Expected behavior**
Number of disks and type should be consistent. 

**Screenshots**
![disks-1](https://user-images.githubusercontent.com/50098566/56946053-68f18280-6b29-11e9-88aa-b7900bbf02c5.png)

![disks-2](https://user-images.githubusercontent.com/50098566/56946064-6db63680-6b29-11e9-83b7-34d5eede04aa.png)

**Foreman - Proxmox versions**
foreman 1.21.3-1
ruby-foreman-fog-proxmox 0.6.0-1
Proxmox cluster 5.3.7

**Additional note**
I think that there are more edge cases here, one time I added few disks and after error on submit I ended up with only default disk.

**Comment by Yamakasi** [comment]
This is a known issue but as far as I know @tristanrobert told earlier this is a (known) Foreman bug, it also happens with other providers.

The same occures that when adding a host and something fails like DHCP, then the whole VM tab is empty/cleared out which should be in cache as well.

I think a Foreman/Browser cache issue.

**Comment by pdzionek** [comment]
@Yamakasi  I guess it doesn't apply to libvirt/kvm plugin, becasue I used it for many years, and never had a similar issue like this :)
