### ISSUE TITLE
Not possible to add compute resource from a different cluster

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#81]
**Describe the bug**
I added two Proxmox nodes to Foreman, which are from the same cluster. After few hours, they stopped working due to ticket renewal issue. So I decided to add another node from a different cluster and I got error invalid PVE ticket. It seems like this plugin is using the same ticket for every proxmox compute resource. I also noticed the same thing with these 2 compute nodes that are from the same cluster. Even though, they were added 1 hour between themselves, they stopped working at the same time.

**To Reproduce**
1. Go to 'Infrastructure -> Compute Resource'
2. Click on 'Create Compute Resource'
3. Fill the data for a host from a different Proxmox cluster than the ones you already added.

**Expected behavior**
Every compute resource should use it is own PVE Ticket.

**Screenshots**
![addcompute2](https://user-images.githubusercontent.com/50098566/56953701-6ac54100-6b3d-11e9-8393-706decc5e3ca.png)

**Foreman - Proxmox versions**
foreman 1.21.3-1
ruby-foreman-fog-proxmox 0.6.0-1
Proxmox cluster 5.3.7

**Comment by Yamakasi** [comment]
I can confirm this, I currently use FireFox Containers for both

**Comment by tristanrobert** [comment]
The renewal ticket is fixed in 0.8.3. You can create so many Proxmox compute resources as you need by cluster (url) and nodes.
