### ISSUE TITLE
Translating Portuguese

### ISSUE THREAD

**Issue by bemanuel** [theforeman/foreman_fog_proxmox#84]
# Translating pt_br

## Prerequisites

Please check (put an X between the brackets) the following items before posting any issue:

* [X] Have you check that no [issue](https://github.com/tristanrobert/foreman_proxmox/issues) already exists and could match yours?

* [X] Have you read the [contributing code](CONTRIBUTING.md)?

## Description

  Contribute translating to portuguese br

## Environment

All

## Version

 Not applied

**Comment by tristanrobert** [comment]
@bemanuel  Done! You can now translate in transifex project: https://www.transifex.com/foremanfogproxmox/public/

**Comment by tristanrobert** [comment]
You can contribute here: https://www.transifex.com/foreman/foreman/language/pt/

**Comment by bemanuel** [comment]
page not found.
Bruno E. A. Silva.

Em seg., 9 de mar. de 2020 às 06:09, Tristan Robert <
notifications@github.com> escreveu:

**Comment by tristanrobert** [comment]
You need to be a member (translator) of this transifex team: https://www.transifex.com/foreman/public/.

**Comment by tristanrobert** [comment]
You choose ressources > foreman_fog_proxmox

**Comment by bemanuel** [comment]
Ok. Now I find it. Thanks.
Bruno E. A. Silva.
Analista de Sistemas.
Bacharel em Sistemas de Informação
MBA Gerência de Projetos
Certified Scrum Master
LPIC-1
SCJP, SE 6
Novell CLA / DCTS ECR
DBA Postgres
-------------------------------
“A caixa dizia: Requer MS Windows ou superior. Então instalei Linux.” -
Sábio Desconhecido
"Alguns prestam serviço/consultoria de Qualidade, os outros vendem licença!"


Em ter., 10 de mar. de 2020 às 04:36, Tristan Robert <
notifications@github.com> escreveu:
