### ISSUE TITLE
Proxmox plugin missing in yum repos for 1.22 version

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#88]
**Describe the bug**
I am not sure if it is the best place to ask, but it seems like the latest plugin version was not released for Centos/Redhat in foreman 1.22. It is present in 1.21 yum repo, but not for the 1.22 version. Was it missed somehow? I know that it is available for Ubuntu, but due to other bugs I had to switch to CentOS 7.

**Comment by tristanrobert** [comment]
0.8.0 packaging is still [waiting to be done](https://github.com/theforeman/foreman-packaging/pull/3746) and I am very busy nowadays to work on 0.8.1. Contributors are welcome!

**Comment by brindapabari** [comment]
![image](https://user-images.githubusercontent.com/48221536/61897146-4c1bdf80-aecb-11e9-88ba-5698bcb8f86a.png)

**Comment by tristanrobert** [comment]
ducplicate #82
