### ISSUE TITLE
semver fails for PVE 6.0-6

### ISSUE THREAD

**Issue by hlawatschek** [theforeman/foreman_fog_proxmox#95]
**Describe the bug**
semver initialization and therefore version check fails for PVE 6.0-6

Proxmox version:
# pvesh get /version
┌─────────┬──────────┐
│ key     │ value    │
├─────────┼──────────┤
│ release │ 6.0      │
├─────────┼──────────┤
│ repoid  │ c71f879f │
├─────────┼──────────┤
│ version │ 6.0-6    │
└─────────┴──────────┘

Semver error message: Proxmox version 6.0-6.6.0 is not semver suitable

BTW: after disabling version check PVE6 seems to work fine.

**Comment by Net-Felix** [comment]
how did you disable version check?

**Comment by hlawatschek** [comment]
Thats a lousy hack.
for testing reasons you could modify 
app/models/foreman_fog_proxmox/proxmox.rb:version_suitable? and return true at the beginning of the function. 

But even better you might want to extend lib/foreman_fog_proxmox/semver.rb to support the new versioning ;-)

**Comment by Xyon** [comment]
To be fair to it, it's not _wrong_, though - the real issue here is that PVE has decided to make their version a non-semver compliant version. With that being the case, it seems like the wrong direction to adapt "semver.rb" to support what isn't really a semver string, is it?

**Comment by Xyon** [comment]
Having said that above, the change that resolves this issue is a single character in the regex in that file, so here's a PR for that anyway (#107)

**Comment by m-bucher** [comment]
Fixed by #99

**Comment by tristanrobert** [comment]
Proxmox 6.0 API is [intentionally rejected](https://github.com/theforeman/foreman_fog_proxmox/blob/bd5c8b90cb64969bf46f14583a866edcb223fbe4/app/models/foreman_fog_proxmox/proxmox_version.rb#L28) by the plugin. Only 5.3, 5.4 are accepted. It would be [modified](https://github.com/fog/fog-proxmox/issues/52) with 0.9.0 fog-proxmox release when it would be suitable (and tested!).
