### ISSUE TITLE
Auth failed when setup Compute resource

### ISSUE THREAD

**Issue by MarkYSA** [theforeman/foreman_fog_proxmox#96]
**Describe the bug**
The Foreman can't connect to Proxmox VE.
curl to proxmox api works fine

I'm receive 401

Expected([200, 204]) <=> Actual(401 Unauthorized) excon.error.response :body => "{\"data\":null}" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "13" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Mon, 02 Sep 2019 11:37:09 GMT" "Expires" => "Mon, 02 Sep 2019 11:37:09 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => "" :local_address => "" :local_port => 58922 :path => "/api2/json/access/ticket" :port => 8006 :reason_phrase => "authentication failure" :remote_ip => "" :status => 401 :status_line => "HTTP/1.1 401 authentication failure\r\n"

CentOS 7
Foreman 1.22
tfm-rubygem-fog-proxmox-0.8.0-1.el7.noarch
tfm-rubygem-foreman_fog_proxmox-0.8.0-1.fm1_22.el7.noarch

# ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

At proxmox I see the following in syslog:

Sep 02 14:42:33  IPCC.xs[9328]: pam_unix(common-auth:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Sep 02 14:42:36  pvedaemon[9328]: authentication failure; rhost= user=root@pam msg=Authentication failure
Sep 02 14:42:36  IPCC.xs[9470]: pam_unix(common-auth:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Sep 02 14:42:38  pvedaemon[9470]: authentication failure; rhost= user=root@pam msg=Authentication failure

**Comment by cospeedster** [comment]
@MarkYSA How did you fixed this?
